[default]
optimizer = true
optimizer_runs = 42069
src = 'contracts'
out = 'artifacts'
libs = ['node_modules']
gas_reports = ["*"]
solc_version = "0.8.11"

[default.optimizer_details]
constantOptimizer = true
yul = true

# See more config options https://github.com/gakonst/foundry/tree/master/config